services:
  - type: web
    name: electripro-backend
    env: java
    rootDir: backend
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SERVER_PORT
        value: 8080
